[[profile]]
name = "laptop"
exec = [
  "swaymsg output 'eDP-1' subpixel none",
]

[[profile.output]]
search = 'eDP-1'
enable = true
mode = "2256x1504@59.999Hz"
position = '0,0'
scale = 1.25
transform = 'normal'
adaptive_sync = false


[[profile]]
name = "docked"

[[profile.output]]
enable = true
search = ["m=0x0BCA", "s=", "v=BOE"]
mode = "2256x1504@59.999Hz"
position = "6096,957"
scale = 1.25
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL 2407WFP", "s=UY5457390H2S ", "v=Dell Inc."]
mode = "1920x1200@59.95Hz"
position = "3304,2160"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=BenQ EW3280U", "s=A1L03067019", "v=BNQ"]
mode = "3840x2160@59.997Hz"
position = "2256,0"
scale = 1.0
transform = "normal"
adaptive_sync = false


[[profile]]
name = "itec"
exec = [
  "swaymsg output 'eDP-1' subpixel none",
  "swaymsg output 'Dell Inc. DELL U2715H GH85D7CN1HPS' subpixel none",
]

[[profile.output]]
search = 'eDP-1'
enable = true
mode = "2256x1504@59.999Hz"
position = '1128,1440'
scale = 1
transform = 'normal'
adaptive_sync = false

[[profile.output]]
search = 'Dell Inc. DELL U2715H GH85D7CN1HPS'
enable = true
mode = "2560x1440@59.951Hz"
position = '1128,0'
scale = 1
transform = 'normal'
adaptive_sync = false

